WIP: Update hastexo_xblock role
hastexo/edx-configuration pull request #50
Opened 2021-01-19 10:38 UTC by mrtmm

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

2021-01-19 16:07 UTC, fghaas requested changes
I have a couple of concerns here and can't wrap my head around one thing; please see inline comments. :)

2021-01-19 16:07 UTC, fghaas commented on playbooks/roles/hastexo_xblock/tasks/main.yml
> +    path: /run/daphne
As far as I remember the `run` directory gets wiped out by systemd on every boot, so this won't survive a reboot. Maybe use a subdirectory of `/edx` instead, like all the other `supervisord` managed edX services do?

2021-01-19 16:07 UTC, fghaas commented on playbooks/roles/hastexo_xblock/defaults/main.yml
> +# Hastexo Guacamole Client
I don't fully understand how exactly these settings result in something that `hastexo_guacamole_client` can read. Can you eloborate on how that works?

2021-01-20 09:39 UTC, mrtmm commented on playbooks/roles/hastexo_xblock/defaults/main.yml
> +# Hastexo Guacamole Client
Well, based on this question I am fairly certain that this does not work and I don't fully understand how to make it work yet :)

2021-01-20 09:40 UTC, mrtmm commented on playbooks/roles/hastexo_xblock/templates/daphne.conf.j2
> +directory={{ edxapp_code_dir }}
Yes, this variable reference and also for using `edxapp_databases`.

2021-01-20 11:04 UTC, fghaas commented on playbooks/roles/hastexo_xblock/defaults/main.yml
> +# Hastexo Guacamole Client
Maybe what you really want here is have a separate `hastexo_guacamole_client` role that perhaps inherits from `edx_django_service`, like (for example) the `blockstore` role does?

2021-01-20 12:19 UTC, mrtmm commented on playbooks/roles/hastexo_xblock/defaults/main.yml
> +# Hastexo Guacamole Client
I'll look into that, thanks!

2021-01-21 09:13 UTC, fghaas commented
Minor suggestion: I think in terms of reviewability (is that a word?) I think it's probably a good idea if you have two commits in this PR: one that adds the `hastexo_guacamole_client` role, and one that rewrites `hastexo_xblock` to ditch the Java servlet bits and uses `hastexo_guacamole_client` instead.

2021-01-21 14:10 UTC, mrtmm commented
@fghaas I've scrolled this back to start from scratch and will add 3 commits here:
1. add the `edx_django_async_service` role
2. add `hastexo_guacamole_client` role that uses the `edx_django_async_service` role
3. update the `hastexo_xblock` to drop the use of the Java guacamole part and use `hastexo_guacamole_client` instead.

2021-01-21 14:17 UTC, fghaas commented
Sounds good, thank you!

2021-01-22 16:19 UTC, fghaas commented on playbooks/roles/hastexo_xblock/tasks/main.yml
> +    path: /run/daphne
I'll mark this as resolved because I believe it is being address with the introduction of the `edx_django_async_service` role.

2021-01-26 14:07 UTC, fghaas commented on playbooks/roles/hastexo_xblock/tasks/main.yml
> +    - daphne
Just making sure I didn't miss an update here: this question here is still open, correct?

2021-01-26 14:20 UTC, mrtmm commented on playbooks/roles/hastexo_xblock/tasks/main.yml
> +    - daphne
I added the task to install Daphne with pip to the `edx_django_async_service` role.

2021-03-02 12:19 UTC, fghaas reviewed
I *think* in the current state of affairs we can make this role play nicely with both the v5 and pre-v5 versions of the XBlock. Please see inline comments for suggestions. Can you give that a look and see if it makes sense to you?

(Comments are worded in the imperative for simplicity. But they're still suggestions.)

2021-03-02 12:19 UTC, fghaas commented on playbooks/roles/hastexo_xblock/meta/main.yml
> +  - hastexo_guacamole_client
Change this to:
```yaml
- role: hastexo_guacamole_client
  when: hastexo_xblock_version is version('5', '>=')
```

2021-03-02 12:19 UTC, fghaas commented on playbooks/roles/hastexo_xblock/tasks/main.yml
> -    - maven
Instead of removing this task, leave it in and add:
```yaml
when: hastexo_xblock_version is version('5', '<')
```

2021-03-02 12:19 UTC, fghaas commented on playbooks/roles/hastexo_xblock/tasks/main.yml
> -  when: NGINX_REDIRECT_TO_HTTPS and not devstack
Instead of removing this task, leave it in and change the `when` condition to:
```yaml
when:
  - NGINX_REDIRECT_TO_HTTPS
  - not devstack
  - hastexo_xblock_version is version('5', '<')
```

(Lists in `when` conditions [are logically ANDed](https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html).)

Also, leave the `web.xml.j2` template in tree.

2021-03-02 12:19 UTC, fghaas commented on playbooks/roles/hastexo_xblock/tasks/main.yml
> -    chdir: "{{ hastexo_xblock_git_checkout }}/guacamole"
Add:
```yaml
when: hastexo_xblock_version is version('5', '<')
```

2021-03-02 12:19 UTC, fghaas commented on playbooks/roles/hastexo_xblock/tasks/main.yml
> -
Instead of removing this task, add:
```yaml
when: hastexo_xblock_version is version('5', '<')
```

2021-03-02 12:19 UTC, fghaas commented on playbooks/roles/hastexo_xblock/tasks/main.yml
> -    state: restarted
Instead of removing this task, add:
```yaml
when: hastexo_xblock_version is version('5', '<')
```

2021-03-02 12:19 UTC, fghaas commented on playbooks/roles/hastexo_xblock/tasks/main.yml
> -
I *think* we concluded that we wanted to still use this task even for the v5 XBlock. In that case, we'd also need the template file back.

If we do not want to use this task for v5, then don't delete it, but instead change the `when` condition to:
```yaml
when:
  - not devstack
  - hastexo_xblock_version is version('5', '<')
```

2021-03-02 15:54 UTC, mrtmm commented on playbooks/roles/hastexo_xblock/tasks/main.yml
> -
We want the same task essentially for v5 too, yes, but we use the one in `edx_django_async_service` role. Added the `when` condition here.

2021-03-02 15:54 UTC, mrtmm commented on playbooks/roles/hastexo_xblock/tasks/main.yml
> -    state: restarted
done

2021-03-02 15:54 UTC, mrtmm commented on playbooks/roles/hastexo_xblock/tasks/main.yml
> -
done

2021-03-02 15:54 UTC, mrtmm commented on playbooks/roles/hastexo_xblock/tasks/main.yml
> -    chdir: "{{ hastexo_xblock_git_checkout }}/guacamole"
done

2021-03-02 15:55 UTC, mrtmm commented on playbooks/roles/hastexo_xblock/tasks/main.yml
> -  when: NGINX_REDIRECT_TO_HTTPS and not devstack
done

2021-03-02 15:55 UTC, mrtmm commented on playbooks/roles/hastexo_xblock/tasks/main.yml
> -    - maven
done

2021-03-03 09:47 UTC, fghaas approved these changes

2021-03-03 09:47 UTC, fghaas commented
I think we're good to go with this one. Do you have any objections to me merging this at this point?

2021-03-03 10:31 UTC, mrtmm commented
No objections, I'm very pleased that we can use this for all versions now :)

2021-03-03 10:41 UTC, fghaas commented
One more nit; could we please get slightly more informative commit messages on the last 2 commits in the PR? :)

2021-03-03 12:08 UTC, mrtmm commented
Sure, added more information to the commit messages.

2021-03-03 16:33 UTC, merged